---
# This named task uses the Ansible template module to generate the based part
# of an MC-LAG configuration
- name: Building EVPN-VXLAN configuration for LEAF / QFX / L2
  template: >
    src=main.conf.j2
    dest={{ build_dir }}/overlay.leaf.qfx.conf.part
